MODULE = USB_module
MODULE_NAME = usb

PACKAGES = led

PRJ_CSRC = 

PRJ_CPPSRC = ros_lib/duration.cpp \
	ros_lib/time.cpp \
	nodes/rosserial.cpp \
	main.cpp
	
PRJ_INC = ros_lib/

include $(R2P_ROOT)/core/r2p.mk

